//! A fake plugin that really gets compiled into a cdylib.
//!
//! It exists for exactly one reason: to prove that the shell generated by `export!` really can
//! become a loadable dynamic library, and is not just calling itself inside one process. It has
//! zero dependencies (apart from the `pmpx-plugin` it tests).

use std::ffi::OsString;

use pmpx_plugin::{CommandSpec, Context, Family, PackageManager, PluginError, Verb};

struct Toy;

impl PackageManager for Toy {
    fn name(&self) -> &str {
        "toy"
    }

    fn family(&self) -> Family {
        Family::NODE
    }

    fn command(
        &self,
        ctx: &Context,
        verb: Verb,
        args: &[OsString],
    ) -> Result<CommandSpec, PluginError> {
        match verb {
            // Echo the matched list as an argument, so the host can verify across the dlopen
            // boundary that `Context::matched` really made it in.
            Verb::Install => {
                let mut spec = CommandSpec::new("toy-bin").arg("add").args(args.iter());
                if ctx.has_matched(".yarnrc.yml") {
                    spec = spec.arg("--berry");
                }
                Ok(spec)
            }

            // Add the project root, to verify paths cross over too
            Verb::Run => Ok(CommandSpec::new("toy-bin").arg(ctx.project_root.clone())),

            // Explicitly unsupported, let the host degrade
            Verb::Exec => Err(PluginError::unsupported_verb(verb)),

            // Deliberately panic, to verify guard and `panic = "unwind"`
            Verb::Test => panic!("this panic must be caught by guard and must never cross extern \"C\""),

            other => Err(PluginError::other(format!("{other} is not implemented yet"))),
        }
    }
}

/// Factory function. This is what the wrapper project generated by crate-plugin-kit calls.
pub fn create() -> Box<dyn PackageManager> {
    Box::new(Toy)
}

pmpx_plugin::export!(create);
