/* Generated by `cargo run -p pmpx-plugin-abi --example gen-abi-files`. Do not edit. */
/* The pmpx plugin ABI, for a plugin written in C (or Zig, or Go...). */
#ifndef PMPX_PLUGIN_H
#define PMPX_PLUGIN_H

#include <stddef.h>
#include <stdint.h>

#ifdef __cplusplus
extern "C" {
#endif

#define PMPX_ABI_MAJOR 3u
#define PMPX_MAX_ITEMS 4096u

/* ---- The numbers ---- */
#define PMPX_VERB_INSTALL 0u
#define PMPX_VERB_REMOVE 1u
#define PMPX_VERB_UPDATE 2u
#define PMPX_VERB_RUN 3u
#define PMPX_VERB_BUILD 4u
#define PMPX_VERB_TEST 5u
#define PMPX_VERB_EXEC 6u
#define PMPX_REASON_SCORED 0u
#define PMPX_REASON_PINNED 1u
#define PMPX_REASON_EXPLICIT 2u
#define PMPX_OK 0u
#define PMPX_ERR_UNSUPPORTED_VERB 1u
#define PMPX_ERR_INVALID_ARGS 2u
#define PMPX_ERR_INTERNAL 3u
#define PMPX_LEVEL_ERROR 0u
#define PMPX_LEVEL_WARN 1u
#define PMPX_LEVEL_INFO 2u
#define PMPX_LEVEL_DEBUG 3u

/* ---- Context keys ---- */
#define PMPX_KEY_ARGS "args"
#define PMPX_KEY_CONFIG_PIN "config.pin"
#define PMPX_KEY_FILE_PREFIX "file."
#define PMPX_KEY_PROJECT_CONFIG_FILES "project.config_files"
#define PMPX_KEY_PROJECT_MATCHED "project.matched"
#define PMPX_KEY_PROJECT_ROOT "project.root"
#define PMPX_KEY_PROJECT_START_DIR "project.start_dir"

/* ---- Capabilities ---- */
#define PMPX_CAP_ATTACH "attach"
#define PMPX_CAP_COMMAND "command"
#define PMPX_CAP_IDENTITY "identity"
#define PMPX_CAP_LOG "log"

/* ---- The data ---- */
typedef struct PmpxStr {
    const uint8_t *ptr; /* null means the value is absent */
    size_t len;
} PmpxStr;

typedef struct PmpxStrSlice {
    const PmpxStr *ptr;
    size_t len;
} PmpxStrSlice;

typedef struct PmpxContext PmpxContext;
typedef struct PmpxHost PmpxHost;

struct PmpxContext {
    size_t size;
    uint32_t verb;
    uint32_t reason;
    uint32_t score;
    size_t (*count)(const PmpxContext *context, PmpxStr key);
    PmpxStr (*get)(const PmpxContext *context, PmpxStr key, size_t index);
    PmpxStr (*name)(const PmpxContext *context, PmpxStr key, size_t index);
};

struct PmpxHost {
    uint32_t abi_major;
    size_t size;
    const void *(*capability)(PmpxStr name);
};

typedef struct PmpxPlugin {
    uint32_t abi_major;
    PmpxStr rustc_version;
    PmpxStr target;
    const void *(*capability)(PmpxStr name);
} PmpxPlugin;

typedef struct PmpxCommand {
    size_t size;
    PmpxStr program;
    PmpxStrSlice args;
    PmpxStr cwd; /* absent means the project root */
} PmpxCommand;

typedef struct PmpxIdentity {
    size_t size;
    PmpxStr (*name)(void);
    PmpxStr (*family)(void);
    void (*free_str)(PmpxStr s);
} PmpxIdentity;

typedef struct PmpxCommandCap {
    size_t size;
    uint32_t (*run)(const PmpxContext *context, PmpxCommand *out);
    void (*free_command)(PmpxCommand *command);
} PmpxCommandCap;

typedef struct PmpxAttach {
    size_t size;
    void (*attach)(const PmpxHost *host);
} PmpxAttach;

typedef struct PmpxLog {
    size_t size;
    void (*write)(uint32_t level, PmpxStr message);
    uint32_t max_level;
} PmpxLog;

/* ---- Layout, checked by the C compiler ---- */
#if defined(__STDC_VERSION__) && __STDC_VERSION__ >= 201112L
_Static_assert(sizeof(PmpxStr) == 16, "PmpxStr size");
_Static_assert(offsetof(PmpxStr, ptr) == 0, "PmpxStr.ptr");
_Static_assert(offsetof(PmpxStr, len) == 8, "PmpxStr.len");
_Static_assert(sizeof(PmpxStrSlice) == 16, "PmpxStrSlice size");
_Static_assert(offsetof(PmpxStrSlice, ptr) == 0, "PmpxStrSlice.ptr");
_Static_assert(offsetof(PmpxStrSlice, len) == 8, "PmpxStrSlice.len");
_Static_assert(sizeof(PmpxContext) == 48, "PmpxContext size");
_Static_assert(offsetof(PmpxContext, size) == 0, "PmpxContext.size");
_Static_assert(offsetof(PmpxContext, verb) == 8, "PmpxContext.verb");
_Static_assert(offsetof(PmpxContext, reason) == 12, "PmpxContext.reason");
_Static_assert(offsetof(PmpxContext, score) == 16, "PmpxContext.score");
_Static_assert(offsetof(PmpxContext, count) == 24, "PmpxContext.count");
_Static_assert(offsetof(PmpxContext, get) == 32, "PmpxContext.get");
_Static_assert(offsetof(PmpxContext, name) == 40, "PmpxContext.name");
_Static_assert(sizeof(PmpxHost) == 24, "PmpxHost size");
_Static_assert(offsetof(PmpxHost, abi_major) == 0, "PmpxHost.abi_major");
_Static_assert(offsetof(PmpxHost, size) == 8, "PmpxHost.size");
_Static_assert(offsetof(PmpxHost, capability) == 16, "PmpxHost.capability");
_Static_assert(sizeof(PmpxPlugin) == 48, "PmpxPlugin size");
_Static_assert(offsetof(PmpxPlugin, abi_major) == 0, "PmpxPlugin.abi_major");
_Static_assert(offsetof(PmpxPlugin, rustc_version) == 8, "PmpxPlugin.rustc_version");
_Static_assert(offsetof(PmpxPlugin, target) == 24, "PmpxPlugin.target");
_Static_assert(offsetof(PmpxPlugin, capability) == 40, "PmpxPlugin.capability");
_Static_assert(sizeof(PmpxCommand) == 56, "PmpxCommand size");
_Static_assert(offsetof(PmpxCommand, size) == 0, "PmpxCommand.size");
_Static_assert(offsetof(PmpxCommand, program) == 8, "PmpxCommand.program");
_Static_assert(offsetof(PmpxCommand, args) == 24, "PmpxCommand.args");
_Static_assert(offsetof(PmpxCommand, cwd) == 40, "PmpxCommand.cwd");
_Static_assert(sizeof(PmpxIdentity) == 32, "PmpxIdentity size");
_Static_assert(offsetof(PmpxIdentity, size) == 0, "PmpxIdentity.size");
_Static_assert(offsetof(PmpxIdentity, name) == 8, "PmpxIdentity.name");
_Static_assert(offsetof(PmpxIdentity, family) == 16, "PmpxIdentity.family");
_Static_assert(offsetof(PmpxIdentity, free_str) == 24, "PmpxIdentity.free_str");
_Static_assert(sizeof(PmpxCommandCap) == 24, "PmpxCommandCap size");
_Static_assert(offsetof(PmpxCommandCap, size) == 0, "PmpxCommandCap.size");
_Static_assert(offsetof(PmpxCommandCap, run) == 8, "PmpxCommandCap.run");
_Static_assert(offsetof(PmpxCommandCap, free_command) == 16, "PmpxCommandCap.free_command");
_Static_assert(sizeof(PmpxAttach) == 16, "PmpxAttach size");
_Static_assert(offsetof(PmpxAttach, size) == 0, "PmpxAttach.size");
_Static_assert(offsetof(PmpxAttach, attach) == 8, "PmpxAttach.attach");
_Static_assert(sizeof(PmpxLog) == 24, "PmpxLog size");
_Static_assert(offsetof(PmpxLog, size) == 0, "PmpxLog.size");
_Static_assert(offsetof(PmpxLog, write) == 8, "PmpxLog.write");
_Static_assert(offsetof(PmpxLog, max_level) == 16, "PmpxLog.max_level");
#endif

#ifdef __cplusplus
}
#endif

#endif /* PMPX_PLUGIN_H */
