//! A fake plugin that really gets dlopen'ed, used by `pmpx`'s end-to-end tests -- it makes
//! the whole "detect -> resolve -> `dlopen` -> cross-ABI call to `command()` -> spawn" chain
//! run for real.
//!
//! It deliberately leaves a few traps to verify the host's fault tolerance: `Exec` returns
//! [`PluginError::unsupported_verb`] (the host must degrade to passing through verbatim for
//! `exec`), `Remove` panics outright (the host must stay alive and get `PMPX_ERR_INTERNAL`),
//! and the remaining verbs return a command that really runs.

use std::ffi::OsString;

use pmpx_plugin::{CommandSpec, Context, Family, PackageManager, PluginError, Verb};

struct FakePm;

impl PackageManager for FakePm {
    fn name(&self) -> &str {
        // Must match `plugin.name` in the manifest, otherwise the host refuses to load it.
        "fakepm"
    }

    fn family(&self) -> Family {
        Family::new("faketest")
    }

    fn command(
        &self,
        ctx: &Context,
        verb: Verb,
        args: &[OsString],
    ) -> Result<CommandSpec, PluginError> {
        // The end-to-end proof that a plugin's own logging reaches the host: pmpx adds the id, and
        // only prints it when a trace was asked for. The context line is the other half -- it shows
        // what the host actually handed over, so a test can assert on the whole struct rather than
        // on one field at a time.
        pmpx_plugin::debug!("mapping {verb} with {} matched file(s)", ctx.matched.len());
        pmpx_plugin::debug::context();

        match verb {
            // A command that is guaranteed to succeed and echo back: the tests assert with it
            // that the root / matched / args crossing the boundary are correct, and that the parts
            // only the host knows (where the person ran from, and why this plugin was picked) got
            // there too.
            Verb::Install | Verb::Build | Verb::Test | Verb::Run | Verb::Update => {
                // What the manifest asked to see, read by the host from the project root: the file
                // is declared in `[context] files`, and "none" is what a missing one looks like.
                let declared = ctx.file_str("fakepm.json").unwrap_or("none");
                let probe = format!(
                    "pmpx-probe root={} matched={} verb={} args={} start={} reason={} score={} \
                     declared={}",
                    ctx.project_root.display(),
                    ctx.matched.join("|"),
                    verb,
                    args.iter()
                        .map(|a| a.to_string_lossy().into_owned())
                        .collect::<Vec<_>>()
                        .join(","),
                    ctx.start_dir.display(),
                    ctx.reason,
                    ctx.score,
                    declared,
                );

                // `echo` exists on both platforms, but on Windows it has to be the cmd builtin
                #[cfg(windows)]
                let spec = CommandSpec::new("cmd").arg("/c").arg("echo").arg(probe);
                #[cfg(not(windows))]
                let spec = CommandSpec::new("echo").arg(probe);

                Ok(spec)
            }

            // Explicitly declared unsupported, so the host has to pass through verbatim itself
            Verb::Exec => Err(PluginError::unsupported_verb(verb)),

            // Verifies the panic fallback. It must never cross `extern "C"`.
            Verb::Remove => panic!("the fake plugin deliberately blows up on remove"),

            // Verb is a closed enum, so this is unreachable in theory; it is kept so that
            // adding a verb later cannot silently slip through
            #[allow(unreachable_patterns)]
            other => Err(PluginError::other(format!("{other} is not implemented"))),
        }
    }
}

/// The factory function. The wrapper generated by crate-plugin-kit calls this too.
pub fn create() -> Box<dyn PackageManager> {
    Box::new(FakePm)
}

pmpx_plugin::export!(create);
