//! Drive the C ABI shell generated by `export!` directly.
//!
//! This test plays the host's role: fill in inputs per `pmpx-plugin`'s contract, read outputs,
//! free memory. It does not `dlopen` (that happens in `tests/cdylib.rs`), but it wires up every
//! line -- including allocating and handing back cross-boundary memory. Only by "really calling
//! once per the ABI" can the code paths generated inside the macro be covered.
//!
//! The fixture plugin and `export!` live at the crate root, because the macro generates the entry
//! symbol as a root item; [`support`] holds the calling helpers, and the tests are grouped by what
//! they exercise.

use std::cell::Cell;
use std::ffi::OsString;

use pmpx_plugin::{CommandSpec, Context, Family, PackageManager, PluginError, Verb};

mod boundary;
mod errors;
mod logging;
mod mapping;
mod support;
mod vtable;

// The switch the `name()` test flips. Thread-local on purpose: one test must not be able to make
// another test's plugin panic while the suite runs in parallel.
thread_local! {
    static PANIC_IN_NAME: Cell<bool> = const { Cell::new(false) };
}

/// Make the fake plugin panic inside `name()`.
pub(crate) fn set_panic_in_name(on: bool) {
    PANIC_IN_NAME.with(|flag| flag.set(on));
}

/// A fake plugin to be driven.
struct Toy;

impl PackageManager for Toy {
    fn name(&self) -> &str {
        // The shim has to contain this: a panic crossing `extern "C"` aborts the whole process.
        if PANIC_IN_NAME.with(Cell::get) {
            panic!("the toy plugin was told to panic in name()");
        }
        "toy"
    }

    fn family(&self) -> Family {
        Family::NODE
    }

    fn command(
        &self,
        ctx: &Context,
        verb: Verb,
        args: &[OsString],
    ) -> Result<CommandSpec, PluginError> {
        // Leave an entry that always panics, to verify guard
        if args.iter().any(|a| a == "panic") {
            panic!("this panic must be caught by guard");
        }

        // The switches the logging tests pull. Same idea as "panic" above: reachable through the
        // ABI only, so nothing else in the suite starts printing.
        if args.iter().any(|a| a == "log") {
            pmpx_plugin::debug!("toy logged for {verb}");
        }
        if args.iter().any(|a| a == "context") {
            pmpx_plugin::debug::context();
        }

        match verb {
            Verb::Install => Ok(CommandSpec::new("toy-bin").arg("add").args(args.iter())),

            // Branch on shape using matched -- without reading any file
            Verb::Run if ctx.has_matched(".yarnrc.yml") => {
                Ok(CommandSpec::new("toy-bin").arg("berry"))
            }
            Verb::Run => Ok(CommandSpec::new("toy-bin").arg("classic")),

            // Declare it explicitly unsupported and let the host degrade
            Verb::Exec => Err(PluginError::unsupported_verb(verb)),

            other => Err(PluginError::other(format!(
                "{other} is not implemented yet"
            ))),
        }
    }
}

/// Factory function. This is the path `export!` wants.
fn create() -> Box<dyn PackageManager> {
    Box::new(Toy)
}

pmpx_plugin::export!(create);
