//! Drive the C ABI shell generated by `export!` directly.
//!
//! This test plays the host's role: fill in inputs per `pmpx-plugin`'s contract, read outputs,
//! free memory. It does not `dlopen` (that happens in `tests/cdylib.rs`), but it wires up every
//! line -- including allocating and handing back cross-boundary memory. Only by "really calling
//! once per the ABI" can the code paths generated inside the macro be covered.

use std::ffi::OsString;

use pmpx_plugin::abi::{self, PmpxCommand, PmpxPluginV1, PmpxStr};
use pmpx_plugin::{CommandSpec, Context, Family, PackageManager, PluginError, Verb};

/// A fake plugin to be driven.
struct Toy;

impl PackageManager for Toy {
    fn name(&self) -> &str {
        "toy"
    }

    fn family(&self) -> Family {
        Family::NODE
    }

    fn command(
        &self,
        ctx: &Context,
        verb: Verb,
        args: &[OsString],
    ) -> Result<CommandSpec, PluginError> {
        // Leave an entry that always panics, to verify guard
        if args.iter().any(|a| a == "panic") {
            panic!("this panic must be caught by guard");
        }

        match verb {
            Verb::Install => Ok(CommandSpec::new("toy-bin").arg("add").args(args.iter())),

            // Branch on shape using matched -- without reading any file
            Verb::Run if ctx.has_matched(".yarnrc.yml") => {
                Ok(CommandSpec::new("toy-bin").arg("berry"))
            }
            Verb::Run => Ok(CommandSpec::new("toy-bin").arg("classic")),

            // Declare it explicitly unsupported and let the host degrade
            Verb::Exec => Err(PluginError::unsupported_verb(verb)),

            other => Err(PluginError::other(format!(
                "{other} is not implemented yet"
            ))),
        }
    }
}

/// Factory function. This is the path `export!` wants.
fn create() -> Box<dyn PackageManager> {
    Box::new(Toy)
}

pmpx_plugin::export!(create);

/// Read a Rust string back from a C string.
///
/// # Safety
/// `s` must be a valid byte range in this process.
unsafe fn read(s: PmpxStr) -> String {
    if s.is_empty() {
        return String::new();
    }
    let bytes = unsafe { std::slice::from_raw_parts(s.ptr, s.len) };
    String::from_utf8(bytes.to_vec()).expect("the tests only pass UTF-8")
}

fn entry() -> &'static PmpxPluginV1 {
    // SAFETY: the entry returns a 'static table.
    unsafe { &*pmpx_plugin_entry_v1() }
}

/// Call `command` once, copy the result into Rust values, then free the plugin's memory per the
/// contract.
fn call_command(
    root: &str,
    matched: &[&str],
    verb: Option<Verb>,
    args: &[&str],
) -> Result<CommandSpec, u32> {
    let e = entry();

    let root_s = PmpxStr {
        ptr: root.as_ptr(),
        len: root.len(),
    };
    let matched_raw: Vec<PmpxStr> = matched
        .iter()
        .map(|s| PmpxStr {
            ptr: s.as_ptr(),
            len: s.len(),
        })
        .collect();
    let args_raw: Vec<PmpxStr> = args
        .iter()
        .map(|s| PmpxStr {
            ptr: s.as_ptr(),
            len: s.len(),
        })
        .collect();

    let mut out = std::mem::MaybeUninit::<PmpxCommand>::uninit();

    // SAFETY: the inputs are allocated by this function and stay alive for the duration of the
    // call; out points at local writable memory.
    // The verb is either a real number or a deliberately out-of-range one.
    let verb_code = verb.map(Verb::to_abi).unwrap_or(99);

    let code = unsafe {
        (e.command)(
            root_s,
            matched_raw.as_ptr(),
            matched_raw.len(),
            verb_code,
            args_raw.as_ptr(),
            args_raw.len(),
            out.as_mut_ptr(),
        )
    };

    if code != abi::PMPX_OK {
        return Err(code);
    }

    // SAFETY: when code == PMPX_OK the plugin guarantees out has been filled in.
    let mut cmd = unsafe { out.assume_init() };

    // Copy this memory out before handing it back to the plugin -- the host only ever reads.
    let spec = unsafe {
        let program = read(cmd.program);
        let cwd = if cmd.cwd.is_empty() {
            None
        } else {
            Some(std::path::PathBuf::from(read(cmd.cwd)))
        };
        let args: Vec<OsString> = (0..cmd.args_len)
            .map(|i| OsString::from(read(*cmd.args.add(i))))
            .collect();

        CommandSpec {
            program: program.into(),
            args,
            cwd,
        }
    };

    // SAFETY: this struct comes from the successful call above and is freed only once.
    unsafe { (e.free_command)(&mut cmd as *mut _) };

    Ok(spec)
}

#[test]
fn the_vtable_reports_a_compatible_abi_version() {
    assert_eq!(entry().abi_version, abi::ABI_VERSION);
}

#[test]
fn build_info_is_visible_for_diagnostics() {
    let e = entry();
    let rustc = unsafe { read(e.rustc_version) };
    let target = unsafe { read(e.target) };

    assert!(rustc.contains("rustc"), "rustc_version = {rustc:?}");
    assert!(target.contains('-'), "target = {target:?}");
}

#[test]
fn name_and_family_come_back_and_are_freed() {
    let e = entry();

    // SAFETY: the returned memory belongs to the plugin; free it with free_str after reading.
    unsafe {
        let name = (e.name)();
        assert_eq!(read(name), "toy");
        (e.free_str)(name);

        let family = (e.family)();
        assert_eq!(read(family), "node");
        (e.free_str)(family);
    }
}

#[test]
fn install_maps_and_forwards_args() {
    let spec = call_command("/proj", &[], Some(Verb::Install), &["serde", "anyhow"])
        .expect("install should succeed");

    assert_eq!(spec.program, OsString::from("toy-bin"));
    assert_eq!(
        spec.args,
        vec![OsString::from("add"), "serde".into(), "anyhow".into()]
    );
    assert_eq!(spec.cwd, None, "cwd should be None when it is not set");
}

#[test]
fn install_with_no_args_still_maps() {
    let spec = call_command("/proj", &[], Some(Verb::Install), &[]).expect("should succeed");
    assert_eq!(spec.args, vec![OsString::from("add")]);
}

/// This is why `Context::matched` exists: the plugin branches on shape with it, without reading
/// any file.
#[test]
fn matched_drives_a_shape_branch() {
    let classic = call_command("/proj", &["yarn.lock"], Some(Verb::Run), &[]).unwrap();
    assert_eq!(classic.args, vec![OsString::from("classic")]);

    let berry = call_command("/proj", &["yarn.lock", ".yarnrc.yml"], Some(Verb::Run), &[]).unwrap();
    assert_eq!(berry.args, vec![OsString::from("berry")]);
}

#[test]
fn unsupported_verb_has_its_own_code() {
    let code = call_command("/proj", &[], Some(Verb::Exec), &[]).unwrap_err();
    assert_eq!(code, abi::PMPX_ERR_UNSUPPORTED_VERB);

    // It must be distinguishable from "other errors" -- the host relies on that to decide whether
    // to degrade
    let other = call_command("/proj", &[], Some(Verb::Build), &[]).unwrap_err();
    assert_eq!(other, abi::PMPX_ERR_INTERNAL);
}

#[test]
fn an_unknown_verb_number_is_rejected() {
    let code = call_command("/proj", &[], None, &[]).unwrap_err();
    assert_eq!(code, abi::PMPX_ERR_INVALID_ARGS);
}

#[test]
fn a_null_out_pointer_is_rejected() {
    let e = entry();
    let root = PmpxStr {
        ptr: "/proj".as_ptr(),
        len: 5,
    };
    let empty: Vec<PmpxStr> = Vec::new();

    // SAFETY: null is passed on purpose here, precisely so that it gets rejected.
    let code = unsafe {
        (e.command)(
            root,
            empty.as_ptr(),
            0,
            Verb::Install.to_abi(),
            empty.as_ptr(),
            0,
            std::ptr::null_mut(),
        )
    };
    assert_eq!(code, abi::PMPX_ERR_INVALID_ARGS);
}

/// A panic must be caught by `guard` and turned into an error code -- it must never cross
/// `extern "C"`. Since Rust 1.81 letting a panic through aborts the process and then this test
/// process would vanish entirely, so "the test finishes" is the conclusion by itself.
///
/// Note: the default panic hook prints the message to stderr, so the line
/// "this panic must be caught by guard" in the test output is expected, not a failure.
#[test]
fn a_panicking_plugin_does_not_take_the_host_down() {
    let code = call_command("/proj", &[], Some(Verb::Install), &["panic"]).unwrap_err();
    assert_eq!(code, abi::PMPX_ERR_INTERNAL);
}

#[test]
fn empty_matched_and_args_are_accepted() {
    let spec = call_command("", &[], Some(Verb::Run), &[]).expect("empty input should work too");
    assert_eq!(spec.args, vec![OsString::from("classic")]);
}

/// A non-UTF-8 path or argument must cross the boundary verbatim (on Unix).
#[cfg(unix)]
#[test]
fn non_utf8_input_survives_the_boundary() {
    use std::os::unix::ffi::OsStrExt;

    // 0xFF is not valid UTF-8, but it is a legitimate path byte
    let raw = [b'/', b'x', 0xFF];
    let root = PmpxStr {
        ptr: raw.as_ptr(),
        len: raw.len(),
    };
    let e = entry();
    let empty: Vec<PmpxStr> = Vec::new();
    let mut out = std::mem::MaybeUninit::<PmpxCommand>::uninit();

    // SAFETY: called per the ABI, with the inputs valid for the whole call.
    let code = unsafe {
        (e.command)(
            root,
            empty.as_ptr(),
            0,
            Verb::Run.to_abi(),
            empty.as_ptr(),
            0,
            out.as_mut_ptr(),
        )
    };
    assert_eq!(code, abi::PMPX_OK);

    // This fake plugin does not look at project_root, so this only proves "it gets in without
    // blowing up"; the real lossless round trip is in the abi unit test
    // (read_os_keeps_arbitrary_bytes).
    let mut cmd = unsafe { out.assume_init() };
    unsafe { (e.free_command)(&mut cmd as *mut _) };

    let os = std::ffi::OsStr::from_bytes(&raw);
    assert_eq!(os.as_bytes(), raw);
}
